name: CI/CD Pipeline Orchestrator

on:
  push:
    branches:
      - 'main'        # Updated from master to main
      - 'feature/**'

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  run-pipeline:
    uses: ./.github/workflows/reusable-devops.yml
    with:
      environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
      deploy_flag: ${{ github.ref_name == 'main' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}